### PR TITLE
Initialize Vuepress docs for a yasa documentation

### PR DESCRIPTION
**Pull request by almogtavor**
It will be easier to maintain the admin UI and let new developers explore if the project has Vuepress docs. I'd wish to merge this branch into a docs-creation branch and the plan in my opinion should be filling the MD docs, and when it'll contain enough content, merge it to master. @kezhenxu94

### CODE REVIEW

**Comment by kezhenxu94** [comment]
> It will be easier to maintain the admin UI and let new developers explore if the project has Vuepress docs. I'd wish to merge this branch into a docs-creation branch and the plan in my opinion should be filling the MD docs, and when it'll contain enough content, merge it to master. @kezhenxu94

Hey @almogtavor , thank you very much for your idea, do you want me to create a branch `docs-creation` and you open PRs targeting that base?

**Comment by almogtavor** [comment]
Absolutely. Also, as for my understanding the project should enter the ASF. Was there any progress on this issue?

**Comment by epugh** [comment]
I love the documentation idea.   YASA is at that difficult point where there is a LOT of potential, but not enough community around it to make it a easy add to Solr.   @kezhenxu94 and I have talked a bit, but I haven't contributed a ton of progress.   

I think where my thinking went wrong was the idea that YASA should first aim to directly replace the Solr Admin.   The more I think about it, YASA should instead attempt to build community by providing features that the current Solr Admin doesn't support, in order to gain more traction in the market.   For example, ParamSets (https://solr.apache.org/guide/8_6/request-parameters-api.html#configuring-request-parameters) can only be  configured via API.   Super powerful feature that my colleague @nathancday has used before, but kind of hidden/lost behind complex API.

**Comment by kezhenxu94** [comment]
@almogtavor I created a branch and change the base of this PR to it.

**Review by kezhenxu94 — APPROVED** [review]

**Comment by almogtavor** [comment]
@epugh Agree about the community. But I don't quite understand the motive behind not moving the project to ASF right now? I think it will be much easier to gain community support that way.

**Comment by kezhenxu94** [comment]
> @epugh Agree about the community. But I don't quite understand the motive behind not moving the project to ASF right now? I think it will be much easier to gain community support that way.

This is a dilemma, to move the project into ASF, the project should have a community (though it can be a small community) to avoid the project being orphaned, but now I am not confident there is a community behind YASA

**Comment by almogtavor** [comment]
@kezhenxu94 I think you right. The project's last feature addition happened a year ago. Another issue that the fact that the project is personal and not in ASF cause to my opinion, is that most Solr users and developers don't even know about the project. If it would be an ASF project it would be more referenced by the Solr main repo, and more developers will get to know it.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I think you right. The project's last feature addition happened a year ago. Another issue that the fact that the project is personal and not in ASF cause to my opinion, is that most Solr users and developers don't even know about the project. If it would be an ASF project it would be more referenced by the Solr main repo, and more developers will get to know it.

Usually, from my experience in Apache SkyWalking, there must be >3 PMC members interested in this project to make it ASF project.

**Comment by almogtavor** [comment]
@kezhenxu94 I think that finding 3 contributors that are ready to become PMC members isn't a hard thing to do. I'm ready to do so it
will be needed. Anyway I think it's a necessary move.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I think that finding 3 contributors that are ready to become PMC members isn't a hard thing to do. I'm ready to do so it will be needed. Anyway I think it's a necessary move.

I appreciate your interest very much 🙇🏻 but I’m not sure how the Solr community and their PMC members think about this, some of them reached out to me but as you see there is no progress now. I’m afraid of it being silent again

**Comment by almogtavor** [comment]
@kezhenxu94 Oh I see. I guess we'll continue to work here and contact them later to see how can we to promote this action?

**Pull request merged**
