### PR TITLE
Feature: add thread dump page

### PR DESCRIPTION
**Pull request by kezhenxu94**
image

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
By future I mean when we get closer to 9.0 Solr release which is out at least until next year it seems.

**Comment by kezhenxu94** [comment]
> I think we should strive to use v2 APIs in the future where possible. 

Sure, agree

**Comment by epugh** [comment]
I've been wrestling with this on the Quepid project as well, we need to start doing the things to push the adoption of the v2 API's!

**Comment by kezhenxu94** [comment]
> I've been wrestling with this on the Quepid project as well, we need to start doing the things to push the adoption of the v2 API's!

Sure agree, have you adopted v2 in Quepid project? Or in progress?

**Comment by epugh** [comment]
I wish!  We have a big dependency on a library called https://github.com/o19s/splainer-search/ that needs updating.  Lots of tech debt there.  Once it is updated, we'll then get it "for free" on both app.quepid.com and on the splainer.io tools.

**Pull request merged**
